// AUTOGENERATED - DO NOT MODIFY


export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2025-07-31 07:00:45.386905 +0300 EEST m=+6.402911376';


export default {
  "id": "scout_agent_store",
  "version": "",
  "name": "Scout Agent Store",
  "icon": "",
  "permissions": null,
  "connect_permissions": null
};
